let countryList = [
   {
      "name": "Afghanistan",
      "iso3": "AFG",
      "iso2": "AF",
      "phone_code": "93",
   },
   {
      "name": "Aland Islands",
      "iso3": "ALA",
      "iso2": "AX",
      "phone_code": "358",
   },
   {
      "name": "Albania",
      "iso3": "ALB",
      "iso2": "AL",
      "phone_code": "355",
   },
   {
      "name": "Algeria",
      "iso3": "DZA",
      "iso2": "DZ",
      "phone_code": "213",
   },
   {
      "name": "American Samoa",
      "iso3": "ASM",
      "iso2": "AS",
      "phone_code": "1",
   },
   {
      "name": "Andorra",
      "iso3": "AND",
      "iso2": "AD",
      "phone_code": "376",
   },
   {
      "name": "Angola",
      "iso3": "AGO",
      "iso2": "AO",
      "phone_code": "244",
   },
   {
      "name": "Anguilla",
      "iso3": "AIA",
      "iso2": "AI",
      "phone_code": "1",
   },
   {
      "name": "Antarctica",
      "iso3": "ATA",
      "iso2": "AQ",
      "phone_code": "672",
   },
   {
      "name": "Antigua and Barbuda",
      "iso3": "ATG",
      "iso2": "AG",
      "phone_code": "1",
   },
   {
      "name": "Argentina",
      "iso3": "ARG",
      "iso2": "AR",
      "phone_code": "54",
   },
   {
      "name": "Armenia",
      "iso3": "ARM",
      "iso2": "AM",
      "phone_code": "374",
   },
   {
      "name": "Aruba",
      "iso3": "ABW",
      "iso2": "AW",
      "phone_code": "297",
   },
   {
      "name": "Australia",
      "iso3": "AUS",
      "iso2": "AU",
      "phone_code": "61",
   },
   {
      "name": "Austria",
      "iso3": "AUT",
      "iso2": "AT",
      "phone_code": "43",
   },
   {
      "name": "Azerbaijan",
      "iso3": "AZE",
      "iso2": "AZ",
      "phone_code": "994",
   },
   {
      "name": "Bahrain",
      "iso3": "BHR",
      "iso2": "BH",
      "phone_code": "973",
   },
   {
      "name": "Bangladesh",
      "iso3": "BGD",
      "iso2": "BD",
      "phone_code": "880",
   },
   {
      "name": "Barbados",
      "iso3": "BRB",
      "iso2": "BB",
      "phone_code": "1",
   },
   {
      "name": "Belarus",
      "iso3": "BLR",
      "iso2": "BY",
      "phone_code": "375",
   },
   {
      "name": "Belgium",
      "iso3": "BEL",
      "iso2": "BE",
      "phone_code": "32",
   },
   {
      "name": "Belize",
      "iso3": "BLZ",
      "iso2": "BZ",
      "phone_code": "501",
   },
   {
      "name": "Benin",
      "iso3": "BEN",
      "iso2": "BJ",
      "phone_code": "229",
   },
   {
      "name": "Bermuda",
      "iso3": "BMU",
      "iso2": "BM",
      "phone_code": "1",
   },
   {
      "name": "Bhutan",
      "iso3": "BTN",
      "iso2": "BT",
      "phone_code": "975",
   },
   {
      "name": "Bolivia",
      "iso3": "BOL",
      "iso2": "BO",
      "phone_code": "591",
   },
   {
      "name": "Bonaire, Sint Eustatius and Saba",
      "iso3": "BES",
      "iso2": "BQ",
      "phone_code": "599",
   },
   {
      "name": "Bosnia and Herzegovina",
      "iso3": "BIH",
      "iso2": "BA",
      "phone_code": "387",
   },
   {
      "name": "Botswana",
      "iso3": "BWA",
      "iso2": "BW",
      "phone_code": "267",
   },
   {
      "name": "Bouvet Island",
      "iso3": "BVT",
      "iso2": "BV",
      "phone_code": "0055",
   },
   {
      "name": "Brazil",
      "iso3": "BRA",
      "iso2": "BR",
      "phone_code": "55",
   },
   {
      "name": "British Indian Ocean Territory",
      "iso3": "IOT",
      "iso2": "IO",
      "phone_code": "246",
   },
   {
      "name": "Brunei",
      "iso3": "BRN",
      "iso2": "BN",
      "phone_code": "673",
   },
   {
      "name": "Bulgaria",
      "iso3": "BGR",
      "iso2": "BG",
      "phone_code": "359",
   },
   {
      "name": "Burkina Faso",
      "iso3": "BFA",
      "iso2": "BF",
      "phone_code": "226",
   },
   {
      "name": "Burundi",
      "iso3": "BDI",
      "iso2": "BI",
      "phone_code": "257",
   },
   {
      "name": "Cambodia",
      "iso3": "KHM",
      "iso2": "KH",
      "phone_code": "855",
   },
   {
      "name": "Cameroon",
      "iso3": "CMR",
      "iso2": "CM",
      "phone_code": "237",
   },
   {
      "name": "Canada",
      "iso3": "CAN",
      "iso2": "CA",
      "phone_code": "1",
   },
   {
      "name": "Cape Verde",
      "iso3": "CPV",
      "iso2": "CV",
      "phone_code": "238",
   },
   {
      "name": "Cayman Islands",
      "iso3": "CYM",
      "iso2": "KY",
      "phone_code": "1",
   },
   {
      "name": "Central African Republic",
      "iso3": "CAF",
      "iso2": "CF",
      "phone_code": "236",
   },
   {
      "name": "Chad",
      "iso3": "TCD",
      "iso2": "TD",
      "phone_code": "235",
   },
   {
      "name": "Chile",
      "iso3": "CHL",
      "iso2": "CL",
      "phone_code": "56",
   },
   {
      "name": "China",
      "iso3": "CHN",
      "iso2": "CN",
      "phone_code": "86",
   },
   {
      "name": "Christmas Island",
      "iso3": "CXR",
      "iso2": "CX",
      "phone_code": "61",
   },
   {
      "name": "Cocos (Keeling) Islands",
      "iso3": "CCK",
      "iso2": "CC",
      "phone_code": "61",
   },
   {
      "name": "Colombia",
      "iso3": "COL",
      "iso2": "CO",
      "phone_code": "57",
   },
   {
      "name": "Comoros",
      "iso3": "COM",
      "iso2": "KM",
      "phone_code": "269",
   },
   {
      "name": "Congo",
      "iso3": "COG",
      "iso2": "CG",
      "phone_code": "242",
   },
   {
      "name": "Cook Islands",
      "iso3": "COK",
      "iso2": "CK",
      "phone_code": "682",
   },
   {
      "name": "Costa Rica",
      "iso3": "CRI",
      "iso2": "CR",
      "phone_code": "506",
   },
   {
      "name": "Cote D'Ivoire (Ivory Coast)",
      "iso3": "CIV",
      "iso2": "CI",
      "phone_code": "225",
   },
   {
      "name": "Croatia",
      "iso3": "HRV",
      "iso2": "HR",
      "phone_code": "385",
   },
   {
      "name": "Cuba",
      "iso3": "CUB",
      "iso2": "CU",
      "phone_code": "53",
   },
   {
      "name": "Curaçao",
      "iso3": "CUW",
      "iso2": "CW",
      "phone_code": "599",
   },
   {
      "name": "Cyprus",
      "iso3": "CYP",
      "iso2": "CY",
      "phone_code": "357",
   },
   {
      "name": "Czech Republic",
      "iso3": "CZE",
      "iso2": "CZ",
      "phone_code": "420",
   },
   {
      "name": "Democratic Republic of the Congo",
      "iso3": "COD",
      "iso2": "CD",
      "phone_code": "243",
   },
   {
      "name": "Denmark",
      "iso3": "DNK",
      "iso2": "DK",
      "phone_code": "45",
   },
   {
      "name": "Djibouti",
      "iso3": "DJI",
      "iso2": "DJ",
      "phone_code": "253",
   },
   {
      "name": "Dominica",
      "iso3": "DMA",
      "iso2": "DM",
      "phone_code": "1",
   },
   {
      "name": "Dominican Republic",
      "iso3": "DOM",
      "iso2": "DO",
      "phone_code": "1",
   },
   {
      "name": "Ecuador",
      "iso3": "ECU",
      "iso2": "EC",
      "phone_code": "593",
   },
   {
      "name": "Egypt",
      "iso3": "EGY",
      "iso2": "EG",
      "phone_code": "20",
   },
   {
      "name": "El Salvador",
      "iso3": "SLV",
      "iso2": "SV",
      "phone_code": "503",
   },
   {
      "name": "Equatorial Guinea",
      "iso3": "GNQ",
      "iso2": "GQ",
      "phone_code": "240",
   },
   {
      "name": "Eritrea",
      "iso3": "ERI",
      "iso2": "ER",
      "phone_code": "291",
   },
   {
      "name": "Estonia",
      "iso3": "EST",
      "iso2": "EE",
      "phone_code": "372",
   },
   {
      "name": "Eswatini",
      "iso3": "SWZ",
      "iso2": "SZ",
      "phone_code": "268",
   },
   {
      "name": "Ethiopia",
      "iso3": "ETH",
      "iso2": "ET",
      "phone_code": "251",
   },
   {
      "name": "Falkland Islands",
      "iso3": "FLK",
      "iso2": "FK",
      "phone_code": "500",
   },
   {
      "name": "Faroe Islands",
      "iso3": "FRO",
      "iso2": "FO",
      "phone_code": "298",
   },
   {
      "name": "Fiji Islands",
      "iso3": "FJI",
      "iso2": "FJ",
      "phone_code": "679",
   },
   {
      "name": "Finland",
      "iso3": "FIN",
      "iso2": "FI",
      "phone_code": "358",
   },
   {
      "name": "France",
      "iso3": "FRA",
      "iso2": "FR",
      "phone_code": "33",
   },
   {
      "name": "French Guiana",
      "iso3": "GUF",
      "iso2": "GF",
      "phone_code": "594",
   },
   {
      "name": "French Polynesia",
      "iso3": "PYF",
      "iso2": "PF",
      "phone_code": "689",
   },
   {
      "name": "French Southern Territories",
      "iso3": "ATF",
      "iso2": "TF",
      "phone_code": "262",
   },
   {
      "name": "Gabon",
      "iso3": "GAB",
      "iso2": "GA",
      "phone_code": "241",
   },
   {
      "name": "Georgia",
      "iso3": "GEO",
      "iso2": "GE",
      "phone_code": "995",
   },
   {
      "name": "Germany",
      "iso3": "DEU",
      "iso2": "DE",
      "phone_code": "49",
   },
   {
      "name": "Ghana",
      "iso3": "GHA",
      "iso2": "GH",
      "phone_code": "233",
   },
   {
      "name": "Gibraltar",
      "iso3": "GIB",
      "iso2": "GI",
      "phone_code": "350",
   },
   {
      "name": "Greece",
      "iso3": "GRC",
      "iso2": "GR",
      "phone_code": "30",
   },
   {
      "name": "Greenland",
      "iso3": "GRL",
      "iso2": "GL",
      "phone_code": "299",
   },
   {
      "name": "Grenada",
      "iso3": "GRD",
      "iso2": "GD",
      "phone_code": "1",
   },
   {
      "name": "Guadeloupe",
      "iso3": "GLP",
      "iso2": "GP",
      "phone_code": "590",
   },
   {
      "name": "Guam",
      "iso3": "GUM",
      "iso2": "GU",
      "phone_code": "1",
   },
   {
      "name": "Guatemala",
      "iso3": "GTM",
      "iso2": "GT",
      "phone_code": "502",
   },
   {
      "name": "Guernsey and Alderney",
      "iso3": "GGY",
      "iso2": "GG",
      "phone_code": "44",
   },
   {
      "name": "Guinea",
      "iso3": "GIN",
      "iso2": "GN",
      "phone_code": "224",
   },
   {
      "name": "Guinea-Bissau",
      "iso3": "GNB",
      "iso2": "GW",
      "phone_code": "245",
   },
   {
      "name": "Guyana",
      "iso3": "GUY",
      "iso2": "GY",
      "phone_code": "592",
   },
   {
      "name": "Haiti",
      "iso3": "HTI",
      "iso2": "HT",
      "phone_code": "509",
   },
   {
      "name": "Heard Island and McDonald Islands",
      "iso3": "HMD",
      "iso2": "HM",
      "phone_code": "672",
   },
   {
      "name": "Honduras",
      "iso3": "HND",
      "iso2": "HN",
      "phone_code": "504",
   },
   {
      "name": "Hong Kong S.A.R.",
      "iso3": "HKG",
      "iso2": "HK",
      "phone_code": "852",
   },
   {
      "name": "Hungary",
      "iso3": "HUN",
      "iso2": "HU",
      "phone_code": "36",
   },
   {
      "name": "Iceland",
      "iso3": "ISL",
      "iso2": "IS",
      "phone_code": "354",
   },
   {
      "name": "India",
      "iso3": "IND",
      "iso2": "IN",
      "phone_code": "91",
   },
   {
      "name": "Indonesia",
      "iso3": "IDN",
      "iso2": "ID",
      "phone_code": "62",
   },
   {
      "name": "Iran",
      "iso3": "IRN",
      "iso2": "IR",
      "phone_code": "98",
   },
   {
      "name": "Iraq",
      "iso3": "IRQ",
      "iso2": "IQ",
      "phone_code": "964",
   },
   {
      "name": "Ireland",
      "iso3": "IRL",
      "iso2": "IE",
      "phone_code": "353",
   },
   {
      "name": "Israel",
      "iso3": "ISR",
      "iso2": "IL",
      "phone_code": "972",
   },
   {
      "name": "Italy",
      "iso3": "ITA",
      "iso2": "IT",
      "phone_code": "39",
   },
   {
      "name": "Jamaica",
      "iso3": "JAM",
      "iso2": "JM",
      "phone_code": "1",
   },
   {
      "name": "Japan",
      "iso3": "JPN",
      "iso2": "JP",
      "phone_code": "81",
   },
   {
      "name": "Jersey",
      "iso3": "JEY",
      "iso2": "JE",
      "phone_code": "44",
   },
   {
      "name": "Jordan",
      "iso3": "JOR",
      "iso2": "JO",
      "phone_code": "962",
   },
   {
      "name": "Kazakhstan",
      "iso3": "KAZ",
      "iso2": "KZ",
      "phone_code": "7",
   },
   {
      "name": "Kenya",
      "iso3": "KEN",
      "iso2": "KE",
      "phone_code": "254",
   },
   {
      "name": "Kiribati",
      "iso3": "KIR",
      "iso2": "KI",
      "phone_code": "686",
   },
   {
      "name": "Kosovo",
      "iso3": "XKX",
      "iso2": "XK",
      "phone_code": "383",
   },
   {
      "name": "Kuwait",
      "iso3": "KWT",
      "iso2": "KW",
      "phone_code": "965",
   },
   {
      "name": "Kyrgyzstan",
      "iso3": "KGZ",
      "iso2": "KG",
      "phone_code": "996",
   },
   {
      "name": "Laos",
      "iso3": "LAO",
      "iso2": "LA",
      "phone_code": "856",
   },
   {
      "name": "Latvia",
      "iso3": "LVA",
      "iso2": "LV",
      "phone_code": "371",
   },
   {
      "name": "Lebanon",
      "iso3": "LBN",
      "iso2": "LB",
      "phone_code": "961",
   },
   {
      "name": "Lesotho",
      "iso3": "LSO",
      "iso2": "LS",
      "phone_code": "266",
   },
   {
      "name": "Liberia",
      "iso3": "LBR",
      "iso2": "LR",
      "phone_code": "231",
   },
   {
      "name": "Libya",
      "iso3": "LBY",
      "iso2": "LY",
      "phone_code": "218",
   },
   {
      "name": "Liechtenstein",
      "iso3": "LIE",
      "iso2": "LI",
      "phone_code": "423",
   },
   {
      "name": "Lithuania",
      "iso3": "LTU",
      "iso2": "LT",
      "phone_code": "370",
   },
   {
      "name": "Luxembourg",
      "iso3": "LUX",
      "iso2": "LU",
      "phone_code": "352",
   },
   {
      "name": "Macau S.A.R.",
      "iso3": "MAC",
      "iso2": "MO",
      "phone_code": "853",
   },
   {
      "name": "Madagascar",
      "iso3": "MDG",
      "iso2": "MG",
      "phone_code": "261",
   },
   {
      "name": "Malawi",
      "iso3": "MWI",
      "iso2": "MW",
      "phone_code": "265",
   },
   {
      "name": "Malaysia",
      "iso3": "MYS",
      "iso2": "MY",
      "phone_code": "60",
   },
   {
      "name": "Maldives",
      "iso3": "MDV",
      "iso2": "MV",
      "phone_code": "960",
   },
   {
      "name": "Mali",
      "iso3": "MLI",
      "iso2": "ML",
      "phone_code": "223",
   },
   {
      "name": "Malta",
      "iso3": "MLT",
      "iso2": "MT",
      "phone_code": "356",
   },
   {
      "name": "Man (Isle of)",
      "iso3": "IMN",
      "iso2": "IM",
      "phone_code": "44",
   },
   {
      "name": "Marshall Islands",
      "iso3": "MHL",
      "iso2": "MH",
      "phone_code": "692",
   },
   {
      "name": "Martinique",
      "iso3": "MTQ",
      "iso2": "MQ",
      "phone_code": "596",
   },
   {
      "name": "Mauritania",
      "iso3": "MRT",
      "iso2": "MR",
      "phone_code": "222",
   },
   {
      "name": "Mauritius",
      "iso3": "MUS",
      "iso2": "MU",
      "phone_code": "230",
   },
   {
      "name": "Mayotte",
      "iso3": "MYT",
      "iso2": "YT",
      "phone_code": "262",
   },
   {
      "name": "Mexico",
      "iso3": "MEX",
      "iso2": "MX",
      "phone_code": "52",
   },
   {
      "name": "Micronesia",
      "iso3": "FSM",
      "iso2": "FM",
      "phone_code": "691",
   },
   {
      "name": "Moldova",
      "iso3": "MDA",
      "iso2": "MD",
      "phone_code": "373",
   },
   {
      "name": "Monaco",
      "iso3": "MCO",
      "iso2": "MC",
      "phone_code": "377",
   },
   {
      "name": "Mongolia",
      "iso3": "MNG",
      "iso2": "MN",
      "phone_code": "976",
   },
   {
      "name": "Montenegro",
      "iso3": "MNE",
      "iso2": "ME",
      "phone_code": "382",
   },
   {
      "name": "Montserrat",
      "iso3": "MSR",
      "iso2": "MS",
      "phone_code": "1",
   },
   {
      "name": "Morocco",
      "iso3": "MAR",
      "iso2": "MA",
      "phone_code": "212",
   },
   {
      "name": "Mozambique",
      "iso3": "MOZ",
      "iso2": "MZ",
      "phone_code": "258",
   },
   {
      "name": "Myanmar",
      "iso3": "MMR",
      "iso2": "MM",
      "phone_code": "95",
   },
   {
      "name": "Namibia",
      "iso3": "NAM",
      "iso2": "NA",
      "phone_code": "264",
   },
   {
      "name": "Nauru",
      "iso3": "NRU",
      "iso2": "NR",
      "phone_code": "674",
   },
   {
      "name": "Nepal",
      "iso3": "NPL",
      "iso2": "NP",
      "phone_code": "977",
   },
   {
      "name": "Netherlands",
      "iso3": "NLD",
      "iso2": "NL",
      "phone_code": "31",
   },
   {
      "name": "New Caledonia",
      "iso3": "NCL",
      "iso2": "NC",
      "phone_code": "687",
   },
   {
      "name": "New Zealand",
      "iso3": "NZL",
      "iso2": "NZ",
      "phone_code": "64",
   },
   {
      "name": "Nicaragua",
      "iso3": "NIC",
      "iso2": "NI",
      "phone_code": "505",
   },
   {
      "name": "Niger",
      "iso3": "NER",
      "iso2": "NE",
      "phone_code": "227",
   },
   {
      "name": "Nigeria",
      "iso3": "NGA",
      "iso2": "NG",
      "phone_code": "234",
   },
   {
      "name": "Niue",
      "iso3": "NIU",
      "iso2": "NU",
      "phone_code": "683",
   },
   {
      "name": "Norfolk Island",
      "iso3": "NFK",
      "iso2": "NF",
      "phone_code": "672",
   },
   {
      "name": "North Korea",
      "iso3": "PRK",
      "iso2": "KP",
      "phone_code": "850",
   },
   {
      "name": "North Macedonia",
      "iso3": "MKD",
      "iso2": "MK",
      "phone_code": "389",
   },
   {
      "name": "Northern Mariana Islands",
      "iso3": "MNP",
      "iso2": "MP",
      "phone_code": "1",
   },
   {
      "name": "Norway",
      "iso3": "NOR",
      "iso2": "NO",
      "phone_code": "47",
   },
   {
      "name": "Oman",
      "iso3": "OMN",
      "iso2": "OM",
      "phone_code": "968",
   },
   {
      "name": "Pakistan",
      "iso3": "PAK",
      "iso2": "PK",
      "phone_code": "92",
   },
   {
      "name": "Palau",
      "iso3": "PLW",
      "iso2": "PW",
      "phone_code": "680",
   },
   {
      "name": "Palestinian Territory Occupied",
      "iso3": "PSE",
      "iso2": "PS",
      "phone_code": "970",
   },
   {
      "name": "Panama",
      "iso3": "PAN",
      "iso2": "PA",
      "phone_code": "507",
   },
   {
      "name": "Papua New Guinea",
      "iso3": "PNG",
      "iso2": "PG",
      "phone_code": "675",
   },
   {
      "name": "Paraguay",
      "iso3": "PRY",
      "iso2": "PY",
      "phone_code": "595",
   },
   {
      "name": "Peru",
      "iso3": "PER",
      "iso2": "PE",
      "phone_code": "51",
   },
   {
      "name": "Philippines",
      "iso3": "PHL",
      "iso2": "PH",
      "phone_code": "63",
   },
   {
      "name": "Pitcairn Island",
      "iso3": "PCN",
      "iso2": "PN",
      "phone_code": "870",
   },
   {
      "name": "Poland",
      "iso3": "POL",
      "iso2": "PL",
      "phone_code": "48",
   },
   {
      "name": "Portugal",
      "iso3": "PRT",
      "iso2": "PT",
      "phone_code": "351",
   },
   {
      "name": "Puerto Rico",
      "iso3": "PRI",
      "iso2": "PR",
      "phone_code": "1",
   },
   {
      "name": "Qatar",
      "iso3": "QAT",
      "iso2": "QA",
      "phone_code": "974",
   },
   {
      "name": "Reunion",
      "iso3": "REU",
      "iso2": "RE",
      "phone_code": "262",
   },
   {
      "name": "Romania",
      "iso3": "ROU",
      "iso2": "RO",
      "phone_code": "40",
   },
   {
      "name": "Russia",
      "iso3": "RUS",
      "iso2": "RU",
      "phone_code": "7",
   },
   {
      "name": "Rwanda",
      "iso3": "RWA",
      "iso2": "RW",
      "phone_code": "250",
   },
   {
      "name": "Saint Helena",
      "iso3": "SHN",
      "iso2": "SH",
      "phone_code": "290",
   },
   {
      "name": "Saint Kitts and Nevis",
      "iso3": "KNA",
      "iso2": "KN",
      "phone_code": "1",
   },
   {
      "name": "Saint Lucia",
      "iso3": "LCA",
      "iso2": "LC",
      "phone_code": "1",
   },
   {
      "name": "Saint Pierre and Miquelon",
      "iso3": "SPM",
      "iso2": "PM",
      "phone_code": "508",
   },
   {
      "name": "Saint Vincent and the Grenadines",
      "iso3": "VCT",
      "iso2": "VC",
      "phone_code": "1",
   },
   {
      "name": "Saint-Barthelemy",
      "iso3": "BLM",
      "iso2": "BL",
      "phone_code": "590",
   },
   {
      "name": "Saint-Martin (French part)",
      "iso3": "MAF",
      "iso2": "MF",
      "phone_code": "590",
   },
   {
      "name": "Samoa",
      "iso3": "WSM",
      "iso2": "WS",
      "phone_code": "685",
   },
   {
      "name": "San Marino",
      "iso3": "SMR",
      "iso2": "SM",
      "phone_code": "378",
   },
   {
      "name": "Sao Tome and Principe",
      "iso3": "STP",
      "iso2": "ST",
      "phone_code": "239",
   },
   {
      "name": "Saudi Arabia",
      "iso3": "SAU",
      "iso2": "SA",
      "phone_code": "966",
   },
   {
      "name": "Senegal",
      "iso3": "SEN",
      "iso2": "SN",
      "phone_code": "221",
   },
   {
      "name": "Serbia",
      "iso3": "SRB",
      "iso2": "RS",
      "phone_code": "381",
   },
   {
      "name": "Seychelles",
      "iso3": "SYC",
      "iso2": "SC",
      "phone_code": "248",
   },
   {
      "name": "Sierra Leone",
      "iso3": "SLE",
      "iso2": "SL",
      "phone_code": "232",
   },
   {
      "name": "Singapore",
      "iso3": "SGP",
      "iso2": "SG",
      "phone_code": "65",
   },
   {
      "name": "Sint Maarten (Dutch part)",
      "iso3": "SXM",
      "iso2": "SX",
      "phone_code": "1721",
   },
   {
      "name": "Slovakia",
      "iso3": "SVK",
      "iso2": "SK",
      "phone_code": "421",
   },
   {
      "name": "Slovenia",
      "iso3": "SVN",
      "iso2": "SI",
      "phone_code": "386",
   },
   {
      "name": "Solomon Islands",
      "iso3": "SLB",
      "iso2": "SB",
      "phone_code": "677",
   },
   {
      "name": "Somalia",
      "iso3": "SOM",
      "iso2": "SO",
      "phone_code": "252",
   },
   {
      "name": "South Africa",
      "iso3": "ZAF",
      "iso2": "ZA",
      "phone_code": "27",
   },
   {
      "name": "South Georgia",
      "iso3": "SGS",
      "iso2": "GS",
      "phone_code": "500",
   },
   {
      "name": "South Korea",
      "iso3": "KOR",
      "iso2": "KR",
      "phone_code": "82",
   },
   {
      "name": "South Sudan",
      "iso3": "SSD",
      "iso2": "SS",
      "phone_code": "211",
   },
   {
      "name": "Spain",
      "iso3": "ESP",
      "iso2": "ES",
      "phone_code": "34",
   },
   {
      "name": "Sri Lanka",
      "iso3": "LKA",
      "iso2": "LK",
      "phone_code": "94",
   },
   {
      "name": "Sudan",
      "iso3": "SDN",
      "iso2": "SD",
      "phone_code": "249",
   },
   {
      "name": "Suriname",
      "iso3": "SUR",
      "iso2": "SR",
      "phone_code": "597",
   },
   {
      "name": "Svalbard and Jan Mayen Islands",
      "iso3": "SJM",
      "iso2": "SJ",
      "phone_code": "47",
   },
   {
      "name": "Sweden",
      "iso3": "SWE",
      "iso2": "SE",
      "phone_code": "46",
   },
   {
      "name": "Switzerland",
      "iso3": "CHE",
      "iso2": "CH",
      "phone_code": "41",
   },
   {
      "name": "Syria",
      "iso3": "SYR",
      "iso2": "SY",
      "phone_code": "963",
   },
   {
      "name": "Taiwan",
      "iso3": "TWN",
      "iso2": "TW",
      "phone_code": "886",
   },
   {
      "name": "Tajikistan",
      "iso3": "TJK",
      "iso2": "TJ",
      "phone_code": "992",
   },
   {
      "name": "Tanzania",
      "iso3": "TZA",
      "iso2": "TZ",
      "phone_code": "255",
   },
   {
      "name": "Thailand",
      "iso3": "THA",
      "iso2": "TH",
      "phone_code": "66",
   },
   {
      "name": "The Bahamas",
      "iso3": "BHS",
      "iso2": "BS",
      "phone_code": "1",
   },
   {
      "name": "The Gambia ",
      "iso3": "GMB",
      "iso2": "GM",
      "phone_code": "220",
   },
   {
      "name": "Timor-Leste",
      "iso3": "TLS",
      "iso2": "TL",
      "phone_code": "670",
   },
   {
      "name": "Togo",
      "iso3": "TGO",
      "iso2": "TG",
      "phone_code": "228",
   },
   {
      "name": "Tokelau",
      "iso3": "TKL",
      "iso2": "TK",
      "phone_code": "690",
   },
   {
      "name": "Tonga",
      "iso3": "TON",
      "iso2": "TO",
      "phone_code": "676",
   },
   {
      "name": "Trinidad and Tobago",
      "iso3": "TTO",
      "iso2": "TT",
      "phone_code": "1",
   },
   {
      "name": "Tunisia",
      "iso3": "TUN",
      "iso2": "TN",
      "phone_code": "216",
   },
   {
      "name": "Turkey",
      "iso3": "TUR",
      "iso2": "TR",
      "phone_code": "90",
   },
   {
      "name": "Turkmenistan",
      "iso3": "TKM",
      "iso2": "TM",
      "phone_code": "993",
   },
   {
      "name": "Turks and Caicos Islands",
      "iso3": "TCA",
      "iso2": "TC",
      "phone_code": "1",
   },
   {
      "name": "Tuvalu",
      "iso3": "TUV",
      "iso2": "TV",
      "phone_code": "688",
   },
   {
      "name": "Uganda",
      "iso3": "UGA",
      "iso2": "UG",
      "phone_code": "256",
   },
   {
      "name": "Ukraine",
      "iso3": "UKR",
      "iso2": "UA",
      "phone_code": "380",
   },
   {
      "name": "United Arab Emirates",
      "iso3": "ARE",
      "iso2": "AE",
      "phone_code": "971",
   },
   {
      "name": "United Kingdom",
      "iso3": "GBR",
      "iso2": "GB",
      "phone_code": "44",
   },
   {
      "name": "United States",
      "iso3": "USA",
      "iso2": "US",
      "phone_code": "1",
   },
   {
      "name": "United States Minor Outlying Islands",
      "iso3": "UMI",
      "iso2": "UM",
      "phone_code": "1",
   },
   {
      "name": "Uruguay",
      "iso3": "URY",
      "iso2": "UY",
      "phone_code": "598",
   },
   {
      "name": "Uzbekistan",
      "iso3": "UZB",
      "iso2": "UZ",
      "phone_code": "998",
   },
   {
      "name": "Vanuatu",
      "iso3": "VUT",
      "iso2": "VU",
      "phone_code": "678",
   },
   {
      "name": "Vatican City State (Holy See)",
      "iso3": "VAT",
      "iso2": "VA",
      "phone_code": "379",
   },
   {
      "name": "Venezuela",
      "iso3": "VEN",
      "iso2": "VE",
      "phone_code": "58",
   },
   {
      "name": "Vietnam",
      "iso3": "VNM",
      "iso2": "VN",
      "phone_code": "84",
   },
   {
      "name": "Virgin Islands (British)",
      "iso3": "VGB",
      "iso2": "VG",
      "phone_code": "1",
   },
   {
      "name": "Virgin Islands (US)",
      "iso3": "VIR",
      "iso2": "VI",
      "phone_code": "1",
   },
   {
      "name": "Wallis and Futuna Islands",
      "iso3": "WLF",
      "iso2": "WF",
      "phone_code": "681",
   },
   {
      "name": "Western Sahara",
      "iso3": "ESH",
      "iso2": "EH",
      "phone_code": "212",
   },
   {
      "name": "Yemen",
      "iso3": "YEM",
      "iso2": "YE",
      "phone_code": "967",
   },
   {
      "name": "Zambia",
      "iso3": "ZMB",
      "iso2": "ZM",
      "phone_code": "260",
   },
   {
      "name": "Zimbabwe",
      "iso3": "ZWE",
      "iso2": "ZW",
      "phone_code": "263",
   },
]